language: php
addons:
  apt:
    packages:
      - locales
      - language-pack-id
      - language-pack-en
php:
  - 5.6
  - 7.0
before_script:
  - "locale -a | grep id"
  - "locale -a | grep en"
  - "composer install"
script:
  - "vendor/bin/phpunit"