name: "Run Tests"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.1
            phpunit: ^10
          - php: 8.0
            phpunit: ^9
          - php: 7.4
            phpunit: ^9
          - php: 5.6
            phpunit: ^5
    name: PHP ${{ matrix.php }} prefer-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, pdo, sqlite, pdo_sqlite
          coverage: none
      - name: Set locale
        run: sudo locale-gen id_ID.UTF-8
      - name: Install dependencies
        run: |
          composer remove "friendsofphp/php-cs-fixer" --dev --no-interaction --no-update
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests
        run: composer test
